---
- hosts: localhost
  gather_facts: no
  tasks:
    - teamcity_project:
        name: marca_test_project
        project_id: MarcaTestProject
        parameters:
          sm.repo.name: marca_test
    - teamcity_project:
        name: branches
        project_id: MarcaTestProject_Branches
        parent_project_id: MarcaTestProject
    - teamcity_build_config:
        name: docs
        build_config_id: MarcaTestProject_Branches_Docs
        project_id: MarcaTestProject_Branches
        template_id: RunPipelineScript
        parameters:
          sm.pipeline.script.name: test.sh
          sm.pipeline.script.args: '"py27" "devmonkeys/anonweb" "%teamcity.build.branch%"'
