---
- hosts: localhost
  gather_facts: no
  tasks:
    - teamcity_project:
        name: marca_test_project  # ==> MarcaTestProject
    - teamcity_project:
        name: branches
        parent_project_id: MarcaTestProject  # ==> MarcaTestProject_Branches
    - teamcity_build_config:
        project_id: MarcaTestProject_Branches
        name: "{{ item }}"
        template_id: RunPipelineScript  # ==> MarcaTestProject_Branches_Docs, etc.
      with_items:
        - docs
        - flake8
        - package
        - py27
